### ISSUE TITLE
Image is stretched after changing resolution

### ISSUE THREAD

**Issue by bezo97** [TheCrystalize/Net3arth#12]
Hello, I'm doing some test renders and found a bug.  
After changing the resolution to a different aspect ratio the image gets stretched. Here's an example with the default params:
![image](https://user-images.githubusercontent.com/26039350/133912296-57e0fe1f-39f1-4aca-9bf9-6b80122ac634.png)
The rectangle in the middle is supposed to be a square but it's wrongly stretched to a 16:9 ratio.

**Comment by EFHIII** [comment]
This is a known issue, but thank you for reporting it.
In your case, adding a
```js
scale(C(1,16/9))
```
to the camera would fix the issue, but this will probably be done by default in the future.
